### ISSUE TITLE
[as2_controller_manager] Fill info message

### ISSUE THREAD

**Issue by pariaspe** [aerostack2/aerostack2#207]
### Feature Description

Info message is mostly empty, timestamp and frames_id required
```
---
header:
  stamp:
    sec: 0
    nanosec: 0
  frame_id: ''
input_control_mode:
  header:
    stamp:
      sec: 0
      nanosec: 0
    frame_id: ''
  yaw_mode: 1
  control_mode: 2
  reference_frame: 1
output_control_mode:
  header:
    stamp:
      sec: 0
      nanosec: 0
    frame_id: ''
  yaw_mode: 2
  control_mode: 3
  reference_frame: 2
---
```
