### ISSUE TITLE
[as2_keyboard_teleoperation] Launch fails when passing a config file

### ISSUE THREAD

**Issue by RPS98** [aerostack2/aerostack2#639]
### ROS2 Version

humble

### Version

main

### Installation

source

### What happened?

Keyboard node crash

### How to reproduce your issue?

Copy from as2_keyboard_teleoperation the  [default config file](https://github.com/aerostack2/aerostack2/blob/main/as2_user_interfaces/as2_keyboard_teleoperation/config/teleop_values_config.yaml):

```
/**:
  ros__parameters:
    namespace: "drone0" # namespace(s) for the drone. Separated by a comma if multiple drones
    use_sim_time: True # use simulation time
    verbose: False # verbose mode
    speed_value: 0.5 # speed value (m/s) for speed mode
    altitude_speed_value: 0.5 # altitude speed value (m/s) for speed mode
    turn_speed_value: 0.5 # turn speed value (rad/s) for speed mode
    position_value: 1.00 # distance value (m) for position mode
    altitude_value: 1.00 # distance altitude value (m) for position mode
    turn_angle_value: 0.78 # turn angle value (rad) for position mode
    drone_frequency: 100.0 # frequency of the drone interface
    speed_frame_id: "earth" # frame id for speed mode
    pose_frame_id: "earth" # frame id for pose mode
    initial_mode: "pose" # initial mode for the teleoperation interface
    modules: "" # additional non-basic modules to be loaded. eg: "follow_reference"
```

Launch keyboard passing this config file:

`ros2 launch as2_keyboard_teleoperation as2_keyboard_teleoperation_launch.py config_file:=keyboard_teleop.yaml 

### Relevant log output

```shell
Then get the following output:


rafa@rafa:~/as2_projects/project_gazebo/config_ground_station(v1.1_rc)$ ros2 launch as2_keyboard_teleoperation as2_keyboard_teleoperation_launch.py config_file:=keyboard_teleop.yaml 
[INFO] [launch]: All log files can be found below /home/rafa/.ros/log/2024-08-12-11-12-19-616266-rafa-43780
[INFO] [launch]: Default logging verbosity is set to INFO
[INFO] [as2_keyboard_teleoperation-1]: process started with pid [43791]
[as2_keyboard_teleoperation-1] /usr/lib/python3/dist-packages/scipy/__init__.py:146: UserWarning: A NumPy version >=1.17.3 and <1.25.0 is required for this version of SciPy (detected version 1.26.4
[as2_keyboard_teleoperation-1]   warnings.warn(f"A NumPy version >={np_minversion} and <{np_maxversion}"
[as2_keyboard_teleoperation-1] usage: keyboard_teleoperation.py [-h] [--speed_value SPEED_VALUE]
[as2_keyboard_teleoperation-1]                                  [--altitude_speed_value ALTITUDE_SPEED_VALUE]
[as2_keyboard_teleoperation-1]                                  [--turn_speed_value TURN_SPEED_VALUE]
[as2_keyboard_teleoperation-1]                                  [--position_value POSITION_VALUE]
[as2_keyboard_teleoperation-1]                                  [--altitude_value ALTITUDE_VALUE]
[as2_keyboard_teleoperation-1]                                  [--turn_angle_value TURN_ANGLE_VALUE]
[as2_keyboard_teleoperation-1]                                  [--speed_frame_id {earth,base_link}]
[as2_keyboard_teleoperation-1]                                  [--pose_frame_id POSE_FRAME_ID]
[as2_keyboard_teleoperation-1]                                  [--initial_mode INITIAL_MODE]
[as2_keyboard_teleoperation-1]                                  [--use_sim_time USE_SIM_TIME]
[as2_keyboard_teleoperation-1]                                  [--verbose VERBOSE] [--namespace NAMESPACE]
[as2_keyboard_teleoperation-1]                                  [--drone_frequency DRONE_FREQUENCY]
[as2_keyboard_teleoperation-1]                                  [--modules MODULES]
[as2_keyboard_teleoperation-1] keyboard_teleoperation.py: error: unrecognized arguments: --/**={}
[ERROR] [as2_keyboard_teleoperation-1]: process has died [pid 43791, exit code 2, cmd 'python3 /home/rafa/aerostack2_ws/install/as2_keyboard_teleoperation/share/as2_keyboard_teleoperation/keyboard_teleoperation.py --namespace= --verbose= --use_sim_time= --speed_value=0.5 --altitude_speed_value=0.5 --turn_speed_value=0.5 --position_value=1.0 --altitude_value=1.0 --turn_angle_value=0.78 --drone_frequency=100.0 --speed_frame_id=earth --pose_frame_id=earth --initial_mode=pose --modules= --/**={}'].
```
