### ISSUE TITLE
[as2_state_estimator] mocap plugin do not redirect pose message to self localization

### ISSUE THREAD

**Issue by javilinos** [aerostack2/aerostack2#738]
### ROS2 Version

humble

### Version

main

### Installation

source

### What happened?

Mocap plugin do not redirect pose message to self localization pose because there is a missmatch between rigid_body_name from the message and rigid_body_name from parameter.

### How to reproduce your issue?

Reproduce rosbag from topic /rigid_bodies which contains the fields as in the following example:
```
---
header:
  stamp:
    sec: 1734522406
    nanosec: 207329557
  frame_id: map
frame_number: 3973
rigidbodies:
- rigid_body_name: '33'
  markers: []
  pose:
    position:
      x: 0.3534073233604431
      y: 0.003978620283305645
      z: 1.046250820159912
    orientation:
      x: -0.9993346929550171
      y: 0.03252308443188667
      z: -0.015770969912409782
      w: 0.004881271626800299
---
```
Then, execute state estimator with mocap plugin as follows: ```ros2 launch as2_state_estimator mocap_pose_state_estimator.launch.py namespace:=drone0 config_file:=config/config.yaml```

With **config/config.yaml** beeing: 
```
/**:
  ros__parameters:
    use_sim_time: False
  state_estimator:
    ros__parameters:
      plugin_name: mocap_pose
      mocap_topic: "/rigid_bodies"
      twist_smooth_filter_cte: 0.1
      orientation_smooth_filter_cte: 0.1
drone0:
  state_estimator:
    ros__parameters:
      rigid_body_name: '33'
```
Published self_localization_pose is:
```
pose:
  position:
    x: 0.0
    y: 0.0
    z: 0.0
  orientation:
    x: 0.0
    y: 0.0
    z: 0.0
    w: 1.0
---
```
When debugging, parameter and message parameter is beeing wrongly compared:

```
[as2_state_estimator_node-1] [INFO] [1736422989.769716943] [drone0.state_estimator]: Rigid body name from parameter: '33'
[as2_state_estimator_node-1] [INFO] [1736422989.769733894] [drone0.state_estimator]: Rigid body name from msg: 33
```

In older branches (pe: #254) the comparison is beeing done correctly with exact previous steps:

```
[as2_state_estimator_node-1] [INFO] [1736424159.557193909] [drone0.state_estimator]: Rigid body name from parameter: 33
[as2_state_estimator_node-1] [INFO] [1736424159.557198148] [drone0.state_estimator]: Rigid body name from msg: 33
```

Issue probably due to parameter loading handling.
